### ISSUE TITLE
Does not work with Alfred 3.3.1

### ISSUE THREAD

**Issue by pkuczynski** [pawelgrzybek/alfred-npm-search#1]
Output from debugger:

```
workflows/user.workflow.9B513A11-F054-41EE-9B97-1EE9D4212800/index.js:2
const fetch = require('node-fetch');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by pkuczynski** [comment]
Similar issue to https://github.com/pawelgrzybek/Alfred-github-search/issues/2

**Comment by pawelgrzybek** [comment]
Cześć Piotrze. Jaka jest wersja node?

**Comment by pawelgrzybek** [comment]
```
node -v
```

**Comment by pawelgrzybek** [comment]
Wińmy tu więc starą wersję node która nie kojarzy co to const :) Od wersji node 4 wszytko powinno śmigać :)

Pozdrawiam
